### ISSUE TITLE
if the master badge doesn't hear back from the baton holder after a minute, issue a new baton holder

### ISSUE THREAD

**Issue by rowr111** [rowr111/cubegarden#49] opened 2019-07-30 18:54 UTC

**Comment by bunnie** [comment] 2019-08-05 07:03
I think this is now built into both the whackamole and LOTR effects? anything else need to be done?

**Comment by rowr111** [comment] 2019-08-05 07:04
yeah you can close this, I think.

**Comment by bunnie** [comment] 2019-08-05 07:08
OK closing as I think the issue is resolved. It's basically an effect-by-effect thing, not universally applied. Basically, if you use batons, add code to issue batons on the master badge. It's just a couple lines, e.g. 

https://github.com/rowr111/cubegarden/blob/master/src/fx/fx-LOTC.c#L220

**Closed as completed by bunnie** 2019-08-05 07:08 UTC
